### ISSUE TITLE
Should double weaving gap closers be impossible?

### ISSUE THREAD

**Issue by SpoonOfTate** [UnknownX7/NoClippy#1]
_**Issue:**_ 
NoClippy allows double weaving with moves that are impossible to double weave due to mandatory animation lock, such as gap closers (Red Mage's Corps-A-Corps, Displacement, Dragoon's Jump, Paladin's Intervene, etc.) leading to impossible double weaving windows.

_**Steps to Reproduce:**_ 
Dragoon, tested at 2.44 GCD.
1. True Thrust
2.Press Jump/Dive and any non-jump/dive oGCD as fast as possible in either order
3. Vorpal Thrust with no clipping

https://drive.google.com/file/d/1yu0RrU6MZJ6aPMsViGXNPmlP1waYLrEa/view?usp=sharing

Red Mage, tested at 2.47 GCD.
1. Veraero, Verthunder (instant)
2. weave Corps-A-Corps and Displacement
3. Veraero, Verthunder again, with no clipping

https://drive.google.com/file/d/1P-kK0yfDjgr9VtggrQVbq4duDWoPUlOH/view?usp=sharing

My normal server ping is anywhere between 200ms and 300ms, but pretty much every guide and resource I've seen has stated that it's otherwise impossible to double weave with a movement action due to animation lock, regardless of latency.

_**Suggested Solution:**_ 
Perhaps add exceptions for movement-based abilities and forcing animation lock to prevent situations like this from happening. I am not a programmer, but this does seem like an unintended consequence of how the plugin works, and could lead to levels of optimization impossible to do in normal play even with near-zero latency.

**Comment by UnknownX7** [comment]
Do you have on these settings?
![image](https://user-images.githubusercontent.com/12263784/131717404-9e9692c0-17b6-4443-8b94-80ba38b967c3.png)
When I do this I still incur at least 75+ ms clips at 2.41 (top clip is my own ping)
![image](https://user-images.githubusercontent.com/12263784/131718621-d070b4d4-54eb-4bcc-b5c9-9cb7c2cfebeb.png)

For DRG (2.46 GCD) I get this 
![image](https://user-images.githubusercontent.com/12263784/131718566-06352228-a61d-4e8a-a546-b9347318861b.png)

I don't necessarily think its impossible to double weave these (the Balance commonly states 20 can weave them with no problems), based on the timings alone it should be 0.6 + 1.1 + 0.6 = 2.3 which leaves 200 ms for additional delay at 2.5, NoClippy should allow them between 2.42-2.48 at the bare minimum assuming it doesn't spike. Additionally, I do have some logs of a 20 ms player attempting it (2.48 GCD),
![image](https://user-images.githubusercontent.com/12263784/131720600-819b5888-4d66-461d-81a9-650cb669583d.png)
![image](https://user-images.githubusercontent.com/12263784/131720608-332d4417-1ff7-41f2-b1fa-82e6b80e9872.png)

However, an interesting observation is that sometimes the delay CAN spike when using these abilities if the ability moves you (might be possible to avoid by being close enough), since you will additionally send a movement packet.

**Comment by SpoonOfTate** [comment]
DRG at 2.44 GCD, the second value is with the "Dry Run" option enabled, though I don't know why it doesn't have the [DRY] tag like in your screenshots;
![image](https://user-images.githubusercontent.com/89931028/131724808-98917bf2-3e89-4028-b4a5-ea769313eb33.png)

RDM at 2.37 GCD (I made a typo in my first post), same values, double weaving Corps > Displacement 
![image](https://user-images.githubusercontent.com/89931028/131725281-b235c84a-54eb-49a3-9112-b622834188d2.png)

However, while testing the above I realized that I didn't have my VPN on. Testing with the VPN and NoClippy resulted in this;
DRG at 2.44 GCD
![image](https://user-images.githubusercontent.com/89931028/131726173-54171890-63ec-42fc-b425-7a35d7f1cfe8.png)

Dry run results;
![image](https://user-images.githubusercontent.com/89931028/131726386-e14b64e7-521e-4474-a627-7185b575f8bf.png)


RDM at 2.37 GCD

![image](https://user-images.githubusercontent.com/89931028/131726744-ead8cece-92a3-4094-83ab-8b3dfb82b7fe.png)

Dry run results; the Wasted GCD at the last bit was user input error
![image](https://user-images.githubusercontent.com/89931028/131726511-69483b59-40e1-4ad6-8a35-e9adcc835fba.png)

**Comment by UnknownX7** [comment]
The [DRY] only appears on the calculations logs (the "Enable Logging" setting). It appears you would be clipping until at least 2.45 for both (the clip value is determined by checking how long is left on your animation lock when the GCD timer finishes, if you were wondering). This gives the server an average of 50 ms response times which is consistent with what I've seen in general, so I don't think this is an impossible weave. I would really need to see someone at 10 ms ping or even below 10 attempt this to confirm though.

**Comment by SpoonOfTate** [comment]
Understood! This is way above my head and I just wanted to report how it felt, though I suppose I was just used to things being slow and unresponsive as molasses.

**Comment by Soreepeong** [comment]
It absolutely depends on which dash action you're using. As far as I know:
* Soten, Intervene: 600ms
* Shukuchi: somewhere between 850ms and 1100ms, can't remember which
* 1100ms: Spineshatter Dive
* 1500ms: Stardiver

Assuming GCD is 2400ms, and server delay is 50ms:
* 0ms. GCD
* 650ms. Intervene
* 1300ms. Intervene
* 1950ms. (next action available)

So, double weaving **some** dash actions without clipping is definitely possible. In fact, I just turned on and connected to Korean client for ≒1ms ping just now and did verify that double intervene just with vanilla client works.

**Comment by SpoonOfTate** [comment]
Thank you for the in-depth reply! This makes a lot of sense. I'm glad networking wizards like you are on the job to help ease the player experience for those of us who live far away from our datacenters of choice.

**Comment by UnknownX7** [comment]
Closing this as these actions have had their animation lock reduced.
