### ISSUE TITLE
In what ways is this different from XivAlexander?

### ISSUE THREAD

**Issue by justin767** [UnknownX7/NoClippy#10]
Hi, my friend just introduced me this software.
I've been using XivAlexander so far, but would love to try this also. What will be the difference?
Thanks in advance!

**Comment by UnknownX7** [comment]
NoClippy is tuned to be very slightly weaker, but has the ability to help with some status effects (various versions of swiftcast and mudras). It's fairly patch resilient, but it does rely on Dalamud being whitelisted for the current patch, which ranges from 20 minutes to a few hours usually. Also, since it's a plugin, it runs inside the game and updates through the plugin installer.
