### ISSUE TITLE
Can not load Noclippy for  6.2CN XIV

### ISSUE THREAD

**Issue by Nonouaa** [UnknownX7/NoClippy#46]
Thanks for your plugin , Noclippy help me a lot .
But I can not use it at soon , I reinstalled CN Xiv 7 days ago and I see Noclippy has been updated to 0.5.9 , So now I can not load it.
Is there any way to help me install the previous version.

**Comment by Nonouaa** [comment]
![image](https://user-images.githubusercontent.com/124560113/216939413-40da8d94-b5ba-4cfa-a1a6-04b0d5db3cc0.png)

**Comment by Nonouaa** [comment]
![T4{VY1MA0{NJ_22F_)A69OA](https://user-images.githubusercontent.com/124560113/216939939-be074190-fe56-4a5c-b02b-ca7f0177690d.png)
![T4{VY1MA0{NJ_22F_)A69OA](https://user-images.githubusercontent.com/124560113/216939985-3271ff7a-aeaf-4cf5-9e52-53f97df3f8c1.png)

**Comment by UnknownX7** [comment]
Unfortunately, it's a bit unviable for me to maintain a plugin for multiple versions of the game (due to differences in the game as well as CN's Dalamud), but I am going through and making my plugins more resistant to fully failing, so hopefully in the future NoClippy could still partially work without any effort across versions. If you would like to try a [previous version](https://github.com/UnknownX7/DalamudPluginRepo/tree/aeb1e4c4d8167fc1078087323d7b31ed02f7470d/plugins/NoClippy) you can browse through the history of the distribution repository and manually overwrite the plugin files in `%AppData%\XIVLauncher\installedPlugins\NoClippy`
